### ISSUE TITLE
new-created apk  crash 

### ISSUE THREAD

**Issue by docxu233333333333333333** [suraj-root/spade#7]
the apk is created successfully,
and it is installed well on phones(one Huawei , one Xiaomi),
but can not open it (new-created apk ) at all,
crashed... ...

and I have tried two apks... ...
![screenshot_2016-10-25-16-18-37-893_com miui bugreport](https://cloud.githubusercontent.com/assets/23053468/19684838/15969fae-9aec-11e6-854d-29f84ab170e9.png)

**Comment by alleyu2** [comment]
The apk crashes while opening. The installation was ok.

**Comment by suraj-root** [comment]
The error indicates that the metasploit's payload class that is called oncreate, the java class seem to be present at compile time, but was not found at runtime. Spade's development is discontinued because of its compatibility issue and its code inefficiency, a new framework will be released in the near future, make sure to check out the same module there. I will definitely check the error out and make a better one.
